{
 "title": "Caddy",
 "description": "Dashboard for Caddy metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Proxy Upstream status",
   "type": "stat",
   "description": "Status of Caddy proxy reverse proxy targets",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caddy_reverse_proxy_upstreams_healthy",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "Per-second request rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "res/sec" } },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "description": "Avg of all types of requests latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(caddy_http_request_duration_seconds_bucket{server=\"srv0\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th percentile request duration",
   "type": "timeseries",
   "description": "Worst request duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(caddy_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}