{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(homeassistant_sensor_humidity_percent[5m])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "UPS input voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_input_voltage_volts[5m])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Indoor Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(homeassistant_sensor_temperature_celsius[5m])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}