{
 "title": "Prometheus UPS metrics",
 "description": "Dashboard for UPS metrics. Currently mix of apcupsd metrics and nut server metrics scraped by prometheus.",
 "tags": [
  "nut",
  "ups",
  "apcups"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ups", "label": "UPS", "query": { "query": "nut_ups_info" } },
   { "name": "smoothing_interval", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_status{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    },
    { "expr": "apcupsd_info", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "UPS input voltage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nut_input_voltage_volts", "legendFormat": "{{ups}}" },
    { "expr": "apcupsd_line_volts", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "Estimated total power consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nut_load[1h]) * nut_real_power_nominal_watts) + sum(avg_over_time(apcupsd_ups_load_percent[1h]) * apcupsd_nominal_power_watts) / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_load{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    },
    { "expr": "apcupsd_ups_load_percent / 100", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_runtime_seconds{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    },
    {
     "expr": "apcupsd_battery_time_left_seconds",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Beeper Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_beeper_status{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Charge [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg_over_time(nut_battery_charge{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    },
    {
     "expr": "avg_over_time(apcupsd_battery_charge_percent[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Runtime [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_battery_runtime_seconds{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    },
    {
     "expr": "avg_over_time(apcupsd_battery_time_left_seconds[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_load{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    },
    {
     "expr": "avg_over_time(apcupsd_ups_load_percent[$smoothing_interval]) / 100",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Voltage [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_battery_voltage_volts{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    },
    {
     "expr": "avg_over_time(apcupsd_battery_volts[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_input_voltage_volts{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    },
    {
     "expr": "avg_over_time(apcupsd_line_volts[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Voltage [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_output_voltage_volts{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    },
    {
     "expr": "avg_over_time(apcupsd_output_volts[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Estimated total power usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Sum Power Usage",
   "type": "timeseries",
   "description": "Estimated summary of power usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (ups)(nut_real_power_nominal_watts * nut_load)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (ups)((apcupsd_ups_load_percent / 100) * apcupsd_nominal_power_watts)",
     "legendFormat": "{{ups}}"
    }
   ]
  }
 ]
}