{
 "title": "Upstream DNS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Upstream DNS queries",
   "type": "timeseries",
   "description": "DNS queries forwarded to public DNS servers from cloudflare",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(coredns_dns_requests_total[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upstream DNS request latency",
   "type": "timeseries",
   "description": "latency in seconds of DNS requests to upstream cloudflared servers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"cloudflared_metrics\"}[5m])) by(server, zone, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream DNS error rate",
   "type": "timeseries",
   "description": "DNS query error rate / $rate_interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(coredns_dns_responses_total{rcode=\"NOERROR\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(coredns_dns_responses_total{rcode=\"NXDOMAIN\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": {
    "content": "# coreDNS metrics\n\ncoreDNS exposes metrics by default on port 9153. I noticed that `cloudflared` metrics include coreDNS metrics so they must be using it under the hood.\n\nHere is some metrics to look for:\n\n### Request latency\n\nThe latency of a request can tell you if there are problems making DNS queries if the latency is high.\n\nThe metric is exposed as a histogram so I found you need to use the operator `histogram_quantile`.\n\nHere is a query to chart request duration in seconds:\n\n```\nhistogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"foo\"}[5m])) by(server, zone, le))\n```\n\n### Error rate\n\nThe error rate can tell you if there is a spike in DNS query failures. This could indicate a problem with upstream servers or your connectivity to the internet.\n\nNXDOMAIN means that a query returns no response.\n\n```\ncoredns_dns_responses_total{rcode=\"NXDOMAIN\"}\n```"
   }
  }
 ]
}