{
 "title": "TV Dashboard",
 "description": "Aggregated dashboard",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "smoothing_interval", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(node_cpu_seconds_total {mode!=\"idle\",instance!~\"10.0.1.2[0-9].+\"}[$smoothing_interval])) by (instance)) / sum(irate(node_cpu_seconds_total{instance!~\"10.0.1.2[0-9].+\"}[$smoothing_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(sum(irate(windows_cpu_time_total {mode!=\"idle\"} [$smoothing_interval])) by (instance)) / sum(irate(windows_cpu_time_total[$smoothing_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "bargauge",
   "description": "Percentage of memory used by the system",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance!~\"10.0.1.2[0-9].+\"} * 100) / node_memory_MemTotal_bytes{instance!~\"10.0.1.2[0-9].+\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - ((windows_os_physical_memory_free_bytes * 100) / windows_cs_physical_memory_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "description": "Number of containers running in kubernetes",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers)",
     "legendFormat": "k8s"
    },
    {
     "expr": "count(container_tasks_state{state=\"running\",name=~\".+\"})",
     "legendFormat": "docker"
    }
   ]
  },
  {
   "title": "Loki- log entries received per second",
   "type": "stat",
   "description": "The total number of log entries received per tenant (not necessarily of lines, as an entry can have more than one line of text).",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(loki_distributor_lines_received_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Prometheus - Total Series",
   "type": "stat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series)"
    }
   ]
  },
  {
   "title": "Network Clients",
   "type": "piechart",
   "description": "Network devices summary by wired or wireless channel connection",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (hostname) (unpoller_client_uptime_seconds)",
     "legendFormat": "Wired"
    },
    {
     "expr": "count by (channel) (unpoller_client_roam_count_total)",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  },
  {
   "title": "Access Point Radio Protocol summary",
   "type": "piechart",
   "description": "Summary of access point radio protocols per wlan client",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (radio_proto) (unpoller_client_roam_count_total)",
     "legendFormat": "{{radio_proto}}"
    }
   ]
  },
  {
   "title": "UPS live Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "apcupsd_info", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "K8s global usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total {mode!=\"idle\",job=\"node-exporter\"}[$smoothing_interval])) / sum(irate(node_cpu_seconds_total{job=\"node-exporter\"}[$smoothing_interval]))",
     "legendFormat": "k8s cpu usage"
    },
    {
     "expr": "100 - (sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * 100) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"}))",
     "legendFormat": "k8s ram usage"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_ups_load_percent", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "UPS Runtime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Network interface activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "-(rate(node_network_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "Rx {{device}} | {{instance}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[$__rate_interval])",
     "legendFormat": "Tx {{device}} | {{instance}}"
    },
    {
     "expr": "rate(windows_net_bytes_sent_total[$__rate_interval]) >0",
     "legendFormat": "Tx {{nic}} | {{instance}}"
    },
    {
     "expr": "-(rate(windows_net_bytes_received_total[$__rate_interval]) >0)",
     "legendFormat": "Rx {{nic}} | {{instance}}"
    }
   ]
  },
  {
   "title": "UPS Input Voltage [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "apcupsd_line_volts", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "IO utilization",
   "type": "timeseries",
   "description": "Percent of I/O device used",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total [$smoothing_interval])\r\n",
     "legendFormat": "{{instance}} | {{device}}"
    }
   ]
  },
  {
   "title": "Partition Utilization",
   "type": "timeseries",
   "description": "Percent of filesystem usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job!=\"node_exporter_vms\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job!=\"node_exporter_vms\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - ((windows_logical_disk_free_bytes {volume !~\"HarddiskVolume.+\"}) / (windows_logical_disk_size_bytes {volume !~\"HarddiskVolume.+\"}))*100",
     "legendFormat": "{{instance}} | Drive: {{volume}}"
    }
   ]
  },
  {
   "title": "Network Gateway Data transfer",
   "type": "timeseries",
   "description": "Rate of data transfer on Network gateway interfaces",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "unpoller_site_transmit_rate_bytes",
     "legendFormat": "{{subsystem}} Tx"
    },
    {
     "expr": "-(unpoller_site_receive_rate_bytes)",
     "legendFormat": "{{subsystem}} Rx"
    }
   ]
  },
  {
   "title": "Access Point Channel utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "unpoller_device_radio_channel_utilization_receive_ratio",
     "legendFormat": "{{radio}} Rx"
    },
    {
     "expr": "unpoller_device_radio_channel_utilization_transmit_ratio",
     "legendFormat": "{{radio}} Tx"
    }
   ]
  },
  {
   "title": "DNS Upstream Response Time",
   "type": "timeseries",
   "description": "Latency of DNS upstream servers compared to localhost",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (upstream) (rate(adguard_processing_time_milliseconds_sum[5m])) / sum by (upstream) (rate(adguard_processing_time_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux System Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job!=\"node-exporter\"} - node_boot_time_seconds{job!=\"node-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Linux Temperature Sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius[$smoothing_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Site Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_lab\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{job=\"win_node_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}